timezone: Africa/Lagos
version: v1.0.0.0.0
cookie: bitballot
os:
path:
address: :4040
adminurl: admin.valued.ng
encryption_keys:
  public: public.pem
  private: private.pem
ethereum:
  network: https://rinkeby.infura.io/wvxLGQSZBjP3Ak7iqt8J
  mnemonic: alcohol begin science tuition clock twelve creek damp betray welcome vessel bounce
dbconfig:
  hostname: localhost
  database: bitballot
  password: bitballot
  username: bitballot
  port: 5433

